<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run() {
        Country::insert([
            [
                'name' =>  'Afganistan',
                'continent' =>  'Azja',
                'capital_city' =>  'Kabul',
                'area' =>  652230,
                'population' =>  30419928,
                'population_density' =>  45.74,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Albania',
                'continent' =>  'Europa',
                'capital_city' =>  'Tirana',
                'area' =>  28748,
                'population' =>  3195000,
                'population_density' =>  111.1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Algieria',
                'continent' =>  'Afryka',
                'capital_city' =>  'Algier',
                'area' =>  2381741,
                'population' =>  34178188,
                'population_density' =>  14.3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Andora',
                'continent' =>  'Europa',
                'capital_city' =>  'Andora',
                'area' =>  468,
                'population' =>  84525,
                'population_density' =>  180.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Angola',
                'continent' =>  'Afryka',
                'capital_city' =>  'Luanda',
                'area' =>  1246700,
                'population' =>  17312000,
                'population_density' =>  14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Antigua i Barbuda',
                'continent' =>  'Ameryka Północna',
                'capital_city' =>  'Saint John’s',
                'area' =>  435.3,
                'population' =>  85420,
                'population_density' =>  196.2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Arabia Saudyjska',
                'continent' =>  'Azja',
                'capital_city' =>  'Rijad',
                'area' =>  2149690,
                'population' =>  28686633,
                'population_density' =>  13.34,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Argentyna',
                'continent' =>  'Ameryka Południowa',
                'capital_city' =>  'Buenos Aires',
                'area' =>  2766890,
                'population' =>  40913584,
                'population_density' =>  15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Armenia',
                'continent' =>  'Azja',
                'capital_city' =>  'Erywań',
                'area' =>  29800,
                'population' =>  3259100,
                'population_density' =>  108.4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Australia',
                'continent' =>  'Australia i Oceania',
                'capital_city' =>  'Canberra',
                'area' =>  7686850,
                'population' =>  22343203,
                'population_density' =>  2.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Austria',
                'continent' =>  'Europa',
                'capital_city' =>  'Wiedeń',
                'area' =>  83871,
                'population' =>  8402549,
                'population_density' =>  100.1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Azerbejdżan',
                'continent' =>  'Azja',
                'capital_city' =>  'Baku',
                'area' =>  86600,
                'population' =>  9493600,
                'population_density' =>  109,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Bahamy',
                'continent' =>  'Ameryka Północna',
                'capital_city' =>  'Nassau',
                'area' =>  13940,
                'population' =>  307451,
                'population_density' =>  21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Bahrajn',
                'continent' =>  'Azja',
                'capital_city' =>  'Manama',
                'area' =>  620,
                'population' =>  1323535,
                'population_density' =>  1189,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Bangladesz',
                'continent' =>  'Azja',
                'capital_city' =>  'Dhaka',
                'area' =>  144000,
                'population' =>  162221000,
                'population_density' =>  1099,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Barbados',
                'continent' =>  'Ameryka Północna',
                'capital_city' =>  'Bridgetown',
                'area' =>  431,
                'population' =>  281968,
                'population_density' =>  654,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Belgia',
                'continent' =>  'Europa',
                'capital_city' =>  'Bruksela',
                'area' =>  30528,
                'population' =>  10584534,
                'population_density' =>  346,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Belize',
                'continent' =>  'Ameryka Północna',
                'capital_city' =>  'Belmopan',
                'area' =>  22966,
                'population' =>  266440,
                'population_density' =>  11.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Benin',
                'continent' =>  'Afryka',
                'capital_city' =>  'Porto-Novo',
                'area' =>  112620,
                'population' =>  8295000,
                'population_density' =>  74,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Bhutan',
                'continent' =>  'Azja',
                'capital_city' =>  'Thimphu',
                'area' =>  47000,
                'population' =>  682321,
                'population_density' =>  14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Białoruś',
                'continent' =>  'Europa',
                'capital_city' =>  'Mińsk',
                'area' =>  207600,
                'population' =>  9474200,
                'population_density' =>  46,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Boliwia',
                'continent' =>  'Ameryka Południowa',
                'capital_city' =>  'Sucre',
                'area' =>  1098580,
                'population' =>  9248000,
                'population_density' =>  8.4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Bośnia i Hercegowina',
                'continent' =>  'Europa',
                'capital_city' =>  'Sarajewo',
                'area' =>  51129,
                'population' =>  4590310,
                'population_density' =>  86,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Botswana',
                'continent' =>  'Afryka',
                'capital_city' =>  'Gaborone',
                'area' =>  600370,
                'population' =>  1842000,
                'population_density' =>  3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Brazylia',
                'continent' =>  'Ameryka Południowa',
                'capital_city' =>  'Brasilia',
                'area' =>  8511965,
                'population' =>  201103330,
                'population_density' =>  23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Brunei',
                'continent' =>  'Azja',
                'capital_city' =>  'Bandar Seri Begawan',
                'area' =>  5770,
                'population' =>  381371,
                'population_density' =>  66,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Bułgaria',
                'continent' =>  'Europa',
                'capital_city' =>  'Sofia',
                'area' =>  110910,
                'population' =>  7531000,
                'population_density' =>  67.9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Burkina Faso',
                'continent' =>  'Afryka',
                'capital_city' =>  'Wagadugu',
                'area' =>  274200,
                'population' =>  15746232,
                'population_density' =>  57.4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Burundi',
                'continent' =>  'Afryka',
                'capital_city' =>  'Gitega',
                'area' =>  27830,
                'population' =>  8691000,
                'population_density' =>  312,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Chile',
                'continent' =>  'Ameryka Południowa',
                'capital_city' =>  'Santiago',
                'area' =>  756950,
                'population' =>  16601707,
                'population_density' =>  22.1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Chiny',
                'continent' =>  'Azja',
                'capital_city' =>  'Pekin',
                'area' =>  9596960,
                'population' =>  1347374752,
                'population_density' =>  140.4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Chorwacja',
                'continent' =>  'Europa',
                'capital_city' =>  'Zagrzeb',
                'area' =>  56542,
                'population' =>  4437460,
                'population_density' =>  79,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Cypr',
                'continent' =>  'Azja',
                'capital_city' =>  'Nikozja',
                'area' =>  9250,
                'population' =>  794600,
                'population_density' =>  132,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Czad',
                'continent' =>  'Afryka',
                'capital_city' =>  'Ndżamena',
                'area' =>  1284000,
                'population' =>  10758945,
                'population_density' =>  7.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Czarnogóra',
                'continent' =>  'Europa',
                'capital_city' =>  'Podgorica',
                'area' =>  13812,
                'population' =>  672180,
                'population_density' =>  48.7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Czechy',
                'continent' =>  'Europa',
                'capital_city' =>  'Praga',
                'area' =>  78866,
                'population' =>  10532770,
                'population_density' =>  133,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Dania',
                'continent' =>  'Europa',
                'capital_city' =>  'Kopenhaga',
                'area' =>  43098.31,
                'population' =>  5540241,
                'population_density' =>  128.4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Demokratyczna Republika Konga',
                'continent' =>  'Afryka',
                'capital_city' =>  'Kinszasa',
                'area' =>  2344858,
                'population' =>  66515000,
                'population_density' =>  28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Dominika',
                'continent' =>  'Ameryka Północna',
                'capital_city' =>  'Roseau',
                'area' =>  754,
                'population' =>  72000,
                'population_density' =>  91.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Dominikana',
                'continent' =>  'Ameryka Północna',
                'capital_city' =>  'Santo Domingo',
                'area' =>  48730,
                'population' =>  9049595,
                'population_density' =>  185,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Dżibuti',
                'continent' =>  'Afryka',
                'capital_city' =>  'Dżibuti',
                'area' =>  23200,
                'population' =>  506221,
                'population_density' =>  21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Egipt',
                'continent' =>  'Afryka, Azja',
                'capital_city' =>  'Kair',
                'area' =>  1001450,
                'population' =>  80471869,
                'population_density' =>  80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Ekwador',
                'continent' =>  'Ameryka Południowa',
                'capital_city' =>  'Quito',
                'area' =>  283560,
                'population' =>  13928000,
                'population_density' =>  49,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Erytrea',
                'continent' =>  'Afryka',
                'capital_city' =>  'Asmara',
                'area' =>  121320,
                'population' =>  5028000,
                'population_density' =>  41,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Estonia',
                'continent' =>  'Europa',
                'capital_city' =>  'Tallinn',
                'area' =>  45226,
                'population' =>  1340122,
                'population_density' =>  29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Eswatini',
                'continent' =>  'Afryka',
                'capital_city' =>  'Mbabane',
                'area' =>  17363,
                'population' =>  1138227,
                'population_density' =>  65.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Etiopia',
                'continent' =>  'Afryka',
                'capital_city' =>  'Addis Abeba',
                'area' =>  1127127,
                'population' =>  81238000,
                'population_density' =>  72,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Fidżi',
                'continent' =>  'Australia i Oceania',
                'capital_city' =>  'Suva',
                'area' =>  18272,
                'population' =>  849000,
                'population_density' =>  46.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Filipiny',
                'continent' =>  'Azja',
                'capital_city' =>  'Manila',
                'area' =>  300000,
                'population' =>  92681000,
                'population_density' =>  309,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Finlandia',
                'continent' =>  'Europa',
                'capital_city' =>  'Helsinki',
                'area' =>  338145,
                'population' =>  5313026,
                'population_density' =>  15.71,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Francja',
                'continent' =>  'Europa',
                'capital_city' =>  'Paryż',
                'area' =>  675417,
                'population' =>  66000000,
                'population_density' =>  98,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Gabon',
                'continent' =>  'Afryka',
                'capital_city' =>  'Libreville',
                'area' =>  267667,
                'population' =>  1454867,
                'population_density' =>  5.4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Gambia',
                'continent' =>  'Afryka',
                'capital_city' =>  'Bandżul',
                'area' =>  11295,
                'population' =>  1690000,
                'population_density' =>  150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Ghana',
                'continent' =>  'Afryka',
                'capital_city' =>  'Akra',
                'area' =>  239460,
                'population' =>  23000000,
                'population_density' =>  96,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Grecja',
                'continent' =>  'Europa',
                'capital_city' =>  'Ateny',
                'area' =>  131957,
                'population' =>  11216708,
                'population_density' =>  85.01,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Grenada',
                'continent' =>  'Ameryka Północna',
                'capital_city' =>  'Saint George’s',
                'area' =>  344,
                'population' =>  89258,
                'population_density' =>  262,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Gruzja',
                'continent' =>  'Azja, Europa',
                'capital_city' =>  'Tbilisi',
                'area' =>  69700,
                'population' =>  4630841,
                'population_density' =>  67,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Gujana',
                'continent' =>  'Ameryka Południowa',
                'capital_city' =>  'Georgetown',
                'area' =>  214970,
                'population' =>  769095,
                'population_density' =>  3.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Gwatemala',
                'continent' =>  'Ameryka Północna',
                'capital_city' =>  'Gwatemala',
                'area' =>  108890,
                'population' =>  12013907,
                'population_density' =>  119,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Gwinea',
                'continent' =>  'Afryka',
                'capital_city' =>  'Konakry',
                'area' =>  245857,
                'population' =>  9950670,
                'population_density' =>  40.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Gwinea Bissau',
                'continent' =>  'Afryka',
                'capital_city' =>  'Bissau',
                'area' =>  36120,
                'population' =>  1475000,
                'population_density' =>  41,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Gwinea Równikowa',
                'continent' =>  'Afryka',
                'capital_city' =>  'Malabo',
                'area' =>  28051.46,
                'population' =>  616459,
                'population_density' =>  22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Haiti',
                'continent' =>  'Ameryka Północna',
                'capital_city' =>  'Port-au-Prince',
                'area' =>  27750,
                'population' =>  8925000,
                'population_density' =>  322,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Hiszpania',
                'continent' =>  'Europa',
                'capital_city' =>  'Madryt',
                'area' =>  504645,
                'population' =>  47150819,
                'population_density' =>  93.43,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Holandia',
                'continent' =>  'Europa',
                'capital_city' =>  'Amsterdam',
                'area' =>  41526,
                'population' =>  16509303,
                'population_density' =>  397.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Honduras',
                'continent' =>  'Ameryka Północna',
                'capital_city' =>  'Tegucigalpa',
                'area' =>  112090,
                'population' =>  7325000,
                'population_density' =>  65,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Indie',
                'continent' =>  'Azja',
                'capital_city' =>  'Nowe Delhi',
                'area' =>  3287590,
                'population' =>  1166079217,
                'population_density' =>  354.7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Indonezja',
                'continent' =>  'Azja',
                'capital_city' =>  'Dżakarta',
                'area' =>  1919440,
                'population' =>  242968342,
                'population_density' =>  124,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Irak',
                'continent' =>  'Azja',
                'capital_city' =>  'Bagdad',
                'area' =>  438317,
                'population' =>  30399572,
                'population_density' =>  69.54,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Iran',
                'continent' =>  'Azja',
                'capital_city' =>  'Teheran',
                'area' =>  1648195,
                'population' =>  70495782,
                'population_density' =>  43,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Irlandia',
                'continent' =>  'Europa',
                'capital_city' =>  'Dublin',
                'area' =>  70273,
                'population' =>  4581269,
                'population_density' =>  63,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Islandia',
                'continent' =>  'Europa',
                'capital_city' =>  'Reykjavík',
                'area' =>  103125,
                'population' =>  306694,
                'population_density' =>  2.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Izrael',
                'continent' =>  'Azja',
                'capital_city' =>  'Jerozolima',
                'area' =>  22072,
                'population' =>  7653600,
                'population_density' =>  351,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Jamajka',
                'continent' =>  'Ameryka Północna',
                'capital_city' =>  'Kingston',
                'area' =>  10991,
                'population' =>  2700000,
                'population_density' =>  245,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Japonia',
                'continent' =>  'Azja',
                'capital_city' =>  'Tokio',
                'area' =>  377835,
                'population' =>  126475664,
                'population_density' =>  336.3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Jemen',
                'continent' =>  'Azja',
                'capital_city' =>  'Sana',
                'area' =>  527968,
                'population' =>  23495361,
                'population_density' =>  44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Jordania',
                'continent' =>  'Azja',
                'capital_city' =>  'Amman',
                'area' =>  92300,
                'population' =>  5759732,
                'population_density' =>  62,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Kambodża',
                'continent' =>  'Azja',
                'capital_city' =>  'Phnom Penh',
                'area' =>  181040,
                'population' =>  13388910,
                'population_density' =>  75,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Kamerun',
                'continent' =>  'Afryka',
                'capital_city' =>  'Jaunde',
                'area' =>  475440,
                'population' =>  18100000,
                'population_density' =>  38,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Kanada',
                'continent' =>  'Ameryka Północna',
                'capital_city' =>  'Ottawa',
                'area' =>  9976140,
                'population' =>  34110000,
                'population_density' =>  3.41,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Katar',
                'continent' =>  'Azja',
                'capital_city' =>  'Doha',
                'area' =>  11437,
                'population' =>  928635,
                'population_density' =>  81,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Kazachstan',
                'continent' =>  'Azja, Europa',
                'capital_city' =>  'Nur-Sułtan',
                'area' =>  2717300,
                'population' =>  15399437,
                'population_density' =>  5.67,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Kenia',
                'continent' =>  'Afryka',
                'capital_city' =>  'Nairobi',
                'area' =>  582650,
                'population' =>  37953840,
                'population_density' =>  68.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Kirgistan',
                'continent' =>  'Azja',
                'capital_city' =>  'Biszkek',
                'area' =>  198500,
                'population' =>  5357000,
                'population_density' =>  27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Kiribati',
                'continent' =>  'Australia i Oceania',
                'capital_city' =>  'Bairiki',
                'area' =>  811,
                'population' =>  103092,
                'population_density' =>  127,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Kolumbia',
                'continent' =>  'Ameryka Południowa',
                'capital_city' =>  'Bogota',
                'area' =>  1139825,
                'population' =>  45730834,
                'population_density' =>  40.1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Komory',
                'continent' =>  'Afryka',
                'capital_city' =>  'Moroni',
                'area' =>  2170,
                'population' =>  671247,
                'population_density' =>  309,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Kongo',
                'continent' =>  'Afryka',
                'capital_city' =>  'Brazzaville',
                'area' =>  342000,
                'population' =>  3756000,
                'population_density' =>  11.2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Korea Południowa',
                'continent' =>  'Azja',
                'capital_city' =>  'Seul',
                'area' =>  99720,
                'population' =>  50062000,
                'population_density' =>  500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Korea Północna',
                'continent' =>  'Azja',
                'capital_city' =>  'Pjongjang',
                'area' =>  120540,
                'population' =>  22757275,
                'population_density' =>  188.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Kostaryka',
                'continent' =>  'Ameryka Północna',
                'capital_city' =>  'San José',
                'area' =>  51100,
                'population' =>  4325000,
                'population_density' =>  85,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Kuba',
                'continent' =>  'Ameryka Północna',
                'capital_city' =>  'Hawana',
                'area' =>  110860,
                'population' =>  11424000,
                'population_density' =>  103,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Kuwejt',
                'continent' =>  'Azja',
                'capital_city' =>  'Kuwejt',
                'area' =>  17818,
                'population' =>  2597000,
                'population_density' =>  122,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Laos',
                'continent' =>  'Azja',
                'capital_city' =>  'Wientian',
                'area' =>  236800,
                'population' =>  6521998,
                'population_density' =>  26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Lesotho',
                'continent' =>  'Afryka',
                'capital_city' =>  'Maseru',
                'area' =>  30355,
                'population' =>  2031348,
                'population_density' =>  67,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Liban',
                'continent' =>  'Azja',
                'capital_city' =>  'Bejrut',
                'area' =>  10452,
                'population' =>  3925502,
                'population_density' =>  375.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Liberia',
                'continent' =>  'Afryka',
                'capital_city' =>  'Monrovia',
                'area' =>  111370,
                'population' =>  3200000,
                'population_density' =>  29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Libia',
                'continent' =>  'Afryka',
                'capital_city' =>  'Trypolis',
                'area' =>  1759540,
                'population' =>  6310434,
                'population_density' =>  3.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Liechtenstein',
                'continent' =>  'Europa',
                'capital_city' =>  'Vaduz',
                'area' =>  160,
                'population' =>  34761,
                'population_density' =>  215,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Litwa',
                'continent' =>  'Europa',
                'capital_city' =>  'Wilno',
                'area' =>  65200,
                'population' =>  3225346,
                'population_density' =>  52,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Luksemburg',
                'continent' =>  'Europa',
                'capital_city' =>  'Luksemburg',
                'area' =>  2586,
                'population' =>  474413,
                'population_density' =>  183.45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Łotwa',
                'continent' =>  'Europa',
                'capital_city' =>  'Ryga',
                'area' =>  64589,
                'population' =>  2224400,
                'population_density' =>  35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Macedonia Północna',
                'continent' =>  'Europa',
                'capital_city' =>  'Skopje',
                'area' =>  25713,
                'population' =>  2061000,
                'population_density' =>  81,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Madagaskar',
                'continent' =>  'Afryka',
                'capital_city' =>  'Antananarywa',
                'area' =>  587040,
                'population' =>  20653556,
                'population_density' =>  34.14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Malawi',
                'continent' =>  'Afryka',
                'capital_city' =>  'Lilongwe',
                'area' =>  118480,
                'population' =>  13600000,
                'population_density' =>  115,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Malediwy',
                'continent' =>  'Azja',
                'capital_city' =>  'Male',
                'area' =>  300,
                'population' =>  396334,
                'population_density' =>  1321,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Malezja',
                'continent' =>  'Azja',
                'capital_city' =>  'Kuala Lumpur',
                'area' =>  329750,
                'population' =>  27730000,
                'population_density' =>  82.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Mali',
                'continent' =>  'Afryka',
                'capital_city' =>  'Bamako',
                'area' =>  1240192,
                'population' =>  12666987,
                'population_density' =>  10.2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Malta',
                'continent' =>  'Europa',
                'capital_city' =>  'Valletta',
                'area' =>  316,
                'population' =>  403532,
                'population_density' =>  1277,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Maroko',
                'continent' =>  'Afryka',
                'capital_city' =>  'Rabat',
                'area' =>  446550,
                'population' =>  34859364,
                'population_density' =>  78.1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Mauretania',
                'continent' =>  'Afryka',
                'capital_city' =>  'Nawakszut',
                'area' =>  1030700,
                'population' =>  3250000,
                'population_density' =>  3.2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Mauritius',
                'continent' =>  'Afryka',
                'capital_city' =>  'Port Louis',
                'area' =>  2045,
                'population' =>  1230602,
                'population_density' =>  601,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Meksyk',
                'continent' =>  'Ameryka Północna',
                'capital_city' =>  'Meksyk',
                'area' =>  1972550,
                'population' =>  112336538,
                'population_density' =>  56.9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Mikronezja',
                'continent' =>  'Australia i Oceania',
                'capital_city' =>  'Palikir',
                'area' =>  702,
                'population' =>  135000,
                'population_density' =>  171,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Mjanma',
                'continent' =>  'Azja',
                'capital_city' =>  'Naypyidaw',
                'area' =>  678500,
                'population' =>  53414374,
                'population_density' =>  78.7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Mołdawia',
                'continent' =>  'Europa',
                'capital_city' =>  'Kiszyniów',
                'area' =>  33843,
                'population' =>  4324450,
                'population_density' =>  128,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Monako',
                'continent' =>  'Europa',
                'capital_city' =>  'Monako',
                'area' =>  1.95,
                'population' =>  32796,
                'population_density' =>  16818,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Mongolia',
                'continent' =>  'Azja',
                'capital_city' =>  'Ułan Bator',
                'area' =>  1564116,
                'population' =>  2736800,
                'population_density' =>  1.75,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Mozambik',
                'continent' =>  'Afryka',
                'capital_city' =>  'Maputo',
                'area' =>  801590,
                'population' =>  21000000,
                'population_density' =>  26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Namibia',
                'continent' =>  'Afryka',
                'capital_city' =>  'Windhuk',
                'area' =>  825418,
                'population' =>  2089000,
                'population_density' =>  2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Nauru',
                'continent' =>  'Australia i Oceania',
                'capital_city' =>  'Yaren',
                'area' =>  21.3,
                'population' =>  14019,
                'population_density' =>  621,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Nepal',
                'continent' =>  'Azja',
                'capital_city' =>  'Katmandu',
                'area' =>  140800,
                'population' =>  28635000,
                'population_density' =>  203,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Niemcy',
                'continent' =>  'Europa',
                'capital_city' =>  'Berlin',
                'area' =>  357114.22,
                'population' =>  81772000,
                'population_density' =>  229,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Niger',
                'continent' =>  'Afryka',
                'capital_city' =>  'Niamey',
                'area' =>  1267000,
                'population' =>  15306252,
                'population_density' =>  12.1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Nigeria',
                'continent' =>  'Afryka',
                'capital_city' =>  'Abudża',
                'area' =>  923768,
                'population' =>  154729000,
                'population_density' =>  167.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Nikaragua',
                'continent' =>  'Ameryka Północna',
                'capital_city' =>  'Managua',
                'area' =>  129494,
                'population' =>  5570000,
                'population_density' =>  43,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Norwegia',
                'continent' =>  'Europa',
                'capital_city' =>  'Oslo',
                'area' =>  324220,
                'population' =>  4769000,
                'population_density' =>  15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Nowa Zelandia',
                'continent' =>  'Australia i Oceania',
                'capital_city' =>  'Wellington',
                'area' =>  268680,
                'population' =>  4393500,
                'population_density' =>  16.35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Oman',
                'continent' =>  'Azja',
                'capital_city' =>  'Maskat',
                'area' =>  309500,
                'population' =>  3312000,
                'population_density' =>  10.7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Pakistan',
                'continent' =>  'Azja',
                'capital_city' =>  'Islamabad',
                'area' =>  803940,
                'population' =>  176242949,
                'population_density' =>  219,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Palau',
                'continent' =>  'Australia i Oceania',
                'capital_city' =>  'Ngerulmud',
                'area' =>  508,
                'population' =>  20800,
                'population_density' =>  44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Panama',
                'continent' =>  'Ameryka Północna',
                'capital_city' =>  'Panama',
                'area' =>  78200,
                'population' =>  3293000,
                'population_density' =>  42,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Papua-Nowa Gwinea',
                'continent' =>  'Australia i Oceania',
                'capital_city' =>  'Port Moresby',
                'area' =>  462840,
                'population' =>  5932000,
                'population_density' =>  12.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Paragwaj',
                'continent' =>  'Ameryka Południowa',
                'capital_city' =>  'Asunción',
                'area' =>  406750,
                'population' =>  6670000,
                'population_density' =>  16.4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Peru',
                'continent' =>  'Ameryka Południowa',
                'capital_city' =>  'Lima',
                'area' =>  1285220,
                'population' =>  29181000,
                'population_density' =>  23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Polska',
                'continent' =>  'Europa',
                'capital_city' =>  'Warszawa',
                'area' =>  322575,
                'population' =>  38200037,
                'population_density' =>  120.92,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Portugalia',
                'continent' =>  'Europa',
                'capital_city' =>  'Lizbona',
                'area' =>  92391,
                'population' =>  10677000,
                'population_density' =>  116,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Republika Południowej Afryki',
                'continent' =>  'Afryka',
                'capital_city' =>  'Pretoria',
                'area' =>  1219912,
                'population' =>  48783000,
                'population_density' =>  40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Republika Środkowoafrykańska',
                'continent' =>  'Afryka',
                'capital_city' =>  'Bangi',
                'area' =>  622984,
                'population' =>  4370000,
                'population_density' =>  7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Republika Zielonego Przylądka',
                'continent' =>  'Afryka',
                'capital_city' =>  'Praia',
                'area' =>  4033,
                'population' =>  499796,
                'population_density' =>  118,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Rosja',
                'continent' =>  'Azja, Europa',
                'capital_city' =>  'Moskwa',
                'area' =>  17075400,
                'population' =>  142914136,
                'population_density' =>  8.4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Rumunia',
                'continent' =>  'Europa',
                'capital_city' =>  'Bukareszt',
                'area' =>  238391,
                'population' =>  22215421,
                'population_density' =>  91,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Rwanda',
                'continent' =>  'Afryka',
                'capital_city' =>  'Kigali',
                'area' =>  26338,
                'population' =>  10186000,
                'population_density' =>  387,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Saint Kitts i Nevis',
                'continent' =>  'Ameryka Północna',
                'capital_city' =>  'Basseterre',
                'area' =>  261,
                'population' =>  38819,
                'population_density' =>  149,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Saint Lucia',
                'continent' =>  'Ameryka Północna',
                'capital_city' =>  'Castries',
                'area' =>  616,
                'population' =>  164213,
                'population_density' =>  266.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Saint Vincent i Grenadyny',
                'continent' =>  'Ameryka Północna',
                'capital_city' =>  'Kingstown',
                'area' =>  389,
                'population' =>  119000,
                'population_density' =>  307,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Salwador',
                'continent' =>  'Ameryka Północna',
                'capital_city' =>  'San Salvador',
                'area' =>  21040,
                'population' =>  6820000,
                'population_density' =>  324,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Samoa',
                'continent' =>  'Australia i Oceania',
                'capital_city' =>  'Apia',
                'area' =>  2944,
                'population' =>  177714,
                'population_density' =>  60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'San Marino',
                'continent' =>  'Europa',
                'capital_city' =>  'San Marino',
                'area' =>  61.6,
                'population' =>  31817,
                'population_density' =>  487,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Senegal',
                'continent' =>  'Afryka',
                'capital_city' =>  'Dakar',
                'area' =>  196190,
                'population' =>  12521851,
                'population_density' =>  64,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Serbia',
                'continent' =>  'Europa',
                'capital_city' =>  'Belgrad',
                'area' =>  77474,
                'population' =>  7498001,
                'population_density' =>  94.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Seszele',
                'continent' =>  'Afryka',
                'capital_city' =>  'Victoria',
                'area' =>  455,
                'population' =>  86525,
                'population_density' =>  190,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Sierra Leone',
                'continent' =>  'Afryka',
                'capital_city' =>  'Freetown',
                'area' =>  71740,
                'population' =>  6150000,
                'population_density' =>  86,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Singapur',
                'continent' =>  'Azja',
                'capital_city' =>  'Singapur',
                'area' =>  692.7,
                'population' =>  4608000,
                'population_density' =>  6652,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Słowacja',
                'continent' =>  'Europa',
                'capital_city' =>  'Bratysława',
                'area' =>  49035,
                'population' =>  5455000,
                'population_density' =>  111,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Słowenia',
                'continent' =>  'Europa',
                'capital_city' =>  'Lublana',
                'area' =>  20273,
                'population' =>  2039399,
                'population_density' =>  99,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Somalia',
                'continent' =>  'Afryka',
                'capital_city' =>  'Mogadiszu',
                'area' =>  637700,
                'population' =>  9559000,
                'population_density' =>  15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Sri Lanka',
                'continent' =>  'Azja',
                'capital_city' =>  'Sri Dźajawardanapura Kotte',
                'area' =>  65610,
                'population' =>  20010000,
                'population_density' =>  320,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Stany Zjednoczone',
                'continent' =>  'Ameryka Północna',
                'capital_city' =>  'Waszyngton',
                'area' =>  9373967,
                'population' =>  311280492,
                'population_density' =>  32.23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Sudan',
                'continent' =>  'Afryka',
                'capital_city' =>  'Chartum',
                'area' =>  1886068,
                'population' =>  30894000,
                'population_density' =>  16.4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Sudan Południowy',
                'continent' =>  'Afryka',
                'capital_city' =>  'Dżuba',
                'area' =>  589745,
                'population' =>  8260490,
                'population_density' =>  0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Surinam',
                'continent' =>  'Ameryka Południowa',
                'capital_city' =>  'Paramaribo',
                'area' =>  163270,
                'population' =>  476000,
                'population_density' =>  2.9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Syria',
                'continent' =>  'Azja',
                'capital_city' =>  'Damaszek',
                'area' =>  185180,
                'population' =>  19748000,
                'population_density' =>  107,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Szwajcaria',
                'continent' =>  'Europa',
                'capital_city' =>  'Berno',
                'area' =>  41290,
                'population' =>  7725200,
                'population_density' =>  186,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Szwecja',
                'continent' =>  'Europa',
                'capital_city' =>  'Sztokholm',
                'area' =>  449964,
                'population' =>  9331523,
                'population_density' =>  20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Tadżykistan',
                'continent' =>  'Azja',
                'capital_city' =>  'Duszanbe',
                'area' =>  143100,
                'population' =>  7100000,
                'population_density' =>  50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Tajlandia',
                'continent' =>  'Azja',
                'capital_city' =>  'Bangkok',
                'area' =>  514000,
                'population' =>  65493000,
                'population_density' =>  127,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Tanzania',
                'continent' =>  'Afryka',
                'capital_city' =>  'Dodoma',
                'area' =>  945087,
                'population' =>  39384223,
                'population_density' =>  42,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Timor Wschodni',
                'continent' =>  'Azja',
                'capital_city' =>  'Dili',
                'area' =>  15007,
                'population' =>  1109000,
                'population_density' =>  74,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Togo',
                'continent' =>  'Afryka',
                'capital_city' =>  'Lomé',
                'area' =>  56785,
                'population' =>  5400000,
                'population_density' =>  95,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Tonga',
                'continent' =>  'Australia i Oceania',
                'capital_city' =>  'Nukuʻalofa',
                'area' =>  748,
                'population' =>  119009,
                'population_density' =>  144,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Trynidad i Tobago',
                'continent' =>  'Ameryka Południowa',
                'capital_city' =>  'Port-of-Spain',
                'area' =>  5128,
                'population' =>  1229000,
                'population_density' =>  206,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Tunezja',
                'continent' =>  'Afryka',
                'capital_city' =>  'Tunis',
                'area' =>  163610,
                'population' =>  10384000,
                'population_density' =>  63.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Turcja',
                'continent' =>  'Azja, Europa',
                'capital_city' =>  'Ankara',
                'area' =>  783562,
                'population' =>  77804122,
                'population_density' =>  92,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Turkmenistan',
                'continent' =>  'Azja',
                'capital_city' =>  'Aszchabad',
                'area' =>  488100,
                'population' =>  5180000,
                'population_density' =>  11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Tuvalu',
                'continent' =>  'Australia i Oceania',
                'capital_city' =>  'Vaiaku',
                'area' =>  26,
                'population' =>  12373,
                'population_density' =>  475.9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Uganda',
                'continent' =>  'Afryka',
                'capital_city' =>  'Kampala',
                'area' =>  236036,
                'population' =>  32369558,
                'population_density' =>  136,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Ukraina',
                'continent' =>  'Europa',
                'capital_city' =>  'Kijów',
                'area' =>  603700,
                'population' =>  45706126,
                'population_density' =>  77,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Urugwaj',
                'continent' =>  'Ameryka Południowa',
                'capital_city' =>  'Montevideo',
                'area' =>  176220,
                'population' =>  3477779,
                'population_density' =>  20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Uzbekistan',
                'continent' =>  'Azja',
                'capital_city' =>  'Taszkent',
                'area' =>  447400,
                'population' =>  27610000,
                'population_density' =>  62,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Vanuatu',
                'continent' =>  'Australia i Oceania',
                'capital_city' =>  'Port Vila',
                'area' =>  12189,
                'population' =>  243304,
                'population_density' =>  20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Watykan',
                'continent' =>  'Europa',
                'capital_city' =>  'Watykan',
                'area' =>  0.44,
                'population' =>  824,
                'population_density' =>  1873,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Wenezuela',
                'continent' =>  'Ameryka Południowa',
                'capital_city' =>  'Caracas',
                'area' =>  916445,
                'population' =>  30102382,
                'population_density' =>  32.85,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Węgry',
                'continent' =>  'Europa',
                'capital_city' =>  'Budapeszt',
                'area' =>  93030,
                'population' =>  9982000,
                'population_density' =>  107,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Wielka Brytania',
                'continent' =>  'Europa',
                'capital_city' =>  'Londyn',
                'area' =>  244820,
                'population' =>  62222000,
                'population_density' =>  254.1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Wietnam',
                'continent' =>  'Azja',
                'capital_city' =>  'Hanoi',
                'area' =>  331051.4,
                'population' =>  86024600,
                'population_density' =>  260,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Włochy',
                'continent' =>  'Europa',
                'capital_city' =>  'Rzym',
                'area' =>  301230,
                'population' =>  60418711,
                'population_density' =>  199.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Wybrzeże Kości Słoniowej',
                'continent' =>  'Afryka',
                'capital_city' =>  'Jamusukro',
                'area' =>  322460,
                'population' =>  18373000,
                'population_density' =>  57,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Wyspy Marshalla',
                'continent' =>  'Australia i Oceania',
                'capital_city' =>  'Majuro',
                'area' =>  181,
                'population' =>  59071,
                'population_density' =>  326,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Wyspy Salomona',
                'continent' =>  'Australia i Oceania',
                'capital_city' =>  'Honiara',
                'area' =>  28450,
                'population' =>  552000,
                'population_density' =>  20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Wyspy Świętego Tomasza i Książęca',
                'continent' =>  'Afryka',
                'capital_city' =>  'São Tomé',
                'area' =>  1001,
                'population' =>  193410,
                'population_density' =>  187,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Zambia',
                'continent' =>  'Afryka',
                'capital_city' =>  'Lusaka',
                'area' =>  752614,
                'population' =>  11500000,
                'population_density' =>  15.3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Zimbabwe',
                'continent' =>  'Afryka',
                'capital_city' =>  'Harare',
                'area' =>  390580,
                'population' =>  12383000,
                'population_density' =>  32,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' =>  'Zjednoczone Emiraty Arabskie',
                'continent' =>  'Azja',
                'capital_city' =>  'Abu Zabi',
                'area' =>  83600,
                'population' =>  4621000,
                'population_density' =>  55,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
